### ISSUE TITLE
Missing the 'media/sounak/4tbdisk/Datasets/quick_draw_125/class_labels.txt' file

### ISSUE THREAD

**Issue by mooooona** [sounakdey/doodle2search#4]
Hello,

When I tried to train the model, it told me that I lacked the ’class_labels.txt‘ file and couldn't find it. I think youmay forgot to upload it. I wish you can upload it or tell me how to generate it. I wish you can reply to me.

Thank you

**Comment by sounakdey** [comment]
I have updated the files in ./src/data
